session:
  lifespan: 24h
serve:
  public:
    base_url: http://127.0.0.1:4455/.ory/kratos/public/
  admin:
    base_url: http://kratos:4434/
selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  whitelisted_return_urls:
    - http://127.0.0.1:4455/
    - http://127.0.0.1:4455/hydra/callback
    - http://127.0.0.1:4455/api/login
  flows:
    error:
      ui_url: http://127.0.0.1:4455/error
    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      after:
        default_browser_return_url: http://127.0.0.1:4455/
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/
    login:
      ui_url: http://127.0.0.1:4455/login
    registration:
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
log:
  level: debug
secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
hashers:
  argon2:
    parallelism: 8
    memory: 488281
    iterations: 8
    salt_length: 16
    key_length: 32
identity:
  default_schema_url: file://identity.traits.schema.json
courier:
  smtp:
    connection_uri: smtps://no-reply@pr1sm.gg:MIRT9yord_pes_buf@smtp.gmail.com:587/
